export default async function generateSitemap(request, context) {
  // 1. Fetch the automated index JSON generated by helix-query.yaml
  const host = new URL(request.url).origin;
  const response = await fetch('${host}/sitemap.json');
  
  if (!response.ok) {
    return new Response('Sitemap data unavailable', { status: 500 });
  }
  
  const data = await response.json();
  const pages = data.data || [];

  // 2. Build the XML structure string
  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

  pages.forEach((page) => {
    // Skip pages explicitly marked as hidden or noindex
    if (page.robots && page.robots.includes('noindex')) return;

    xml += '  <url>\n';
    xml += '    <loc>${host}${page.path}</loc>\n';
    if (page.lastmod) {
        xml += `    <lastmod>${new Date(page.lastmod).toISOString().split('T')[0]}</lastmod>\n`;    }
    xml += '    <changefreq>weekly</changefreq>\n';
    xml += '  </url>\n';
  });

  xml += '</urlset>';

  // 3. Return the response with correct XML headers
  return new Response(xml, {
    status: 200,
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=86400', // Cache on edge for 24 hours
    },
  });
}
